// src/index.ts

import { promises as fs } from "fs";
import path from "path";
import simpleGit from "simple-git";
import { Octokit } from "@octokit/rest";
import OpenAI from "openai";
import dotenv from "dotenv";

// Load env vars from .env
dotenv.config();
const openai  = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

async function main() {
  const repoUrl = process.argv[2];
  const targetFiles = process.argv.slice(3);
  if (!repoUrl) {
    console.error("Usage: codex-test-gen <github-repo-url>");
    process.exit(1);
  }

  // 1) Clone into temp dir
  const workDir = path.join(process.cwd(), `tmp-${Date.now()}`);
  console.log("🔄 Cloning into", workDir);
  await simpleGit().clone(repoUrl, workDir);

  // 2) Detect JS vs Python
  let isJS = false;
  try {
    await fs.stat(path.join(workDir, "package.json"));
    isJS = true;
  } catch {
    isJS = false;
  }
  const testExt = isJS ? ".test.js" : "_test.py";

  // 3) Recursively find source files
  async function walk(dir: string): Promise<string[]> {
    let results: string[] = [];
    for (const ent of await fs.readdir(dir, { withFileTypes: true })) {
      const full = path.join(dir, ent.name);
      if (ent.isDirectory()) {
        results = results.concat(await walk(full));
      } else if (full.endsWith(isJS ? ".js" : ".py")) {
        results.push(full);
      }
    }
    return results;
  }
  const sources = targetFiles.map((rel: string) => path.join(workDir, rel));


  // 4) Generate tests per file
  for (const file of sources) {
    console.log("✍️  Generating tests for", path.relative(workDir, file));
    const code = await fs.readFile(file, "utf8");
    const chat = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: `Write ${isJS ? "Jest" : "pytest"} tests.` },
        { role: "user",    content: code }
      ]
    });
    const testCode = chat.choices[0].message.content || "// no output";
    const testPath = file
      .replace(/\.[^.]+$/, testExt)
      .replace(workDir, path.join(workDir, "test"));
    await fs.mkdir(path.dirname(testPath), { recursive: true });
    await fs.writeFile(testPath, testCode);
    console.log("✅  Wrote", path.relative(workDir, testPath));
  }

  // 5) Commit, push & open PR
  const git = simpleGit(workDir);
  const branch = `codex-tests-${Date.now()}`;
  await git.checkoutLocalBranch(branch);
  await git.add("./*");
  await git.commit("chore: add AI-generated unit tests");
  await git.push("origin", branch);

  // Extract owner/repo from URL
  const m = /github\.com[/:](.+?)\/(.+?)(?:\.git)?$/.exec(repoUrl);
  if (!m) throw new Error("Could not parse GitHub URL");
  const [, owner, repo] = m;
  const pr = await octokit.pulls.create({
    owner, repo,
    head: branch,
    base: "main",
    title: "AI-generated unit tests",
    body: "Generated by OpenAI Codex."
  });
  console.log("🎉  PR created:", pr.data.html_url);
}

main().catch(e => {
  console.error("💥 Error:", e.message || e);
  process.exit(1);
});
